# Generated by Django 5.1.2 on 2024-10-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_content_image_remove_content_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='age_restriction',
            field=models.BooleanField(default=False, verbose_name='Возрастные ограничения'),
        ),
    ]
