# Generated by Django 5.1.2 on 2024-12-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_userprofile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_publish_content',
            field=models.BooleanField(default=True, verbose_name='Может публиковать контент'),
        ),
    ]
